config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new, :create]
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_comments_counter

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_likes_counter

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: 'post_id'
  has_many :likes, foreign_key: 'post_id'

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_posts_counter

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def recent_comments
    comments.last(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  after_initialize :set_defaults
  def recent_posts
    posts.last(3)
  end

  private

  def set_defaults
    self.posts_counter ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?
  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |field|
      field.permit(:name, :photo, :bio, :posts_counter, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @user = current_user
  end

  def create
    @post = Post.find(params[:post_id] || params[:id])
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post = @post

    respond_to do |format|
      if @comment.save!
        format.html do
          redirect_to user_post_url(current_user, @post), notice: 'Comment was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
    @user = current_user
  end

  def create
    @post = Post.find(params[:post_id] || params[:id])
    @like = Like.new(post_id: @post.id, author_id: current_user.id)
    @like.author_id = current_user.id

    respond_to do |format|
      if @like.save
        format.html { redirect_to user_post_url(current_user, @post), notice: 'Like was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_url(@post.author_id, @post), notice: 'Post was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text, :comments_counter, :likes_counter)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<section class="container grid">
    <p class="post-title">Add New Comment :</p>
    <%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, class: "form-control grid" do |form| %>
    
        <%= form.label :text %>
        <%= form.text_area :text, placeholder: "Type your comment here!", rows: 20, required: true,  class: "form-post-text" %>        
    
    <div class = "btn__holder">
        <%= form.submit "Save", class: "button" %>
    </div>
    <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp - Khuraijam'</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div  role="alert"><%= notice %></div>
  <div  role="alert"><%= alert %></div>
    <%= yield %>
  </body>
</html>

app/views/likes/new.html.erb
<section class="container grid">
    <%= form_with(model: @like, url: user_post_likes_path) do |form| %>
    <%= form.submit 'Add Like', class: "button" %>
    <% end %>
</section>

app/views/posts/index.html.erb
<section class="container grid">  

    <%= render 'shared/user_card', user:@user %> 

    <% @posts.each do |post| %>
        <article class="cards cards--posts">
            <%= link_to user_post_path(@user.id, post.id) do %>
                <%= render 'shared/post_content', post:post, post_content:post.text.first(250).concat('...'), writer:'' %>
            <% end %>
            <%= render('shared/post_comments', post:post) if post.comments_counter.positive? %>            
        </article>    

    <% end %>   

    <div class="btn__holder">
        <%= button_to 'Add New Post', new_user_post_url(id: @user.id), method: :get, class: "button"%>
        <button class="button">
            Pagination
        </button>
    </div>

</section>

app/views/posts/new.html.erb
<section class="container grid">
    <h2 class="post-title">Add New Post :</h2>
    <%= form_with model: @post, url: user_posts_path, method: :post, local: true, class: "form-control grid" do |form| %>

        <%= form.hidden_field :comments_counter, value: 0 %>
        <%= form.hidden_field :likes_counter, value: 0 %>
        
        <div class="grid">
            <%= form.label :title %>
            <%= form.text_field :title, placeholder: "Title", required: true, class: "form-post-title" %>        
        </div>

        <div class="grid">
            <%= form.label :text %>
            <%= form.text_area :text, placeholder: "Type your post here!", rows: 20, required: true,  class: "form-post-text" %>        
        </div>

        <div>
            <%= form.submit "Save", class: "button" %>
        </div>
    <% end %>
</section>

app/views/posts/show.html.erb
<section class="container grid">    
    <article class="cards cards--posts">
        <%= render 'shared/post_content', post:@post, post_content:@post.text, writer:"by ".concat(@post.author.name) %>        
        <%= render('shared/post_comments', post:@post) if @post.comments_counter.positive? %> 
        <div class="button_to btn__holder">
            <%= button_to "Add Comment", new_user_post_comment_path(@post.author, @post), method: :get, class: "button" %>
            <%= render :partial => 'shared/new_like' %>
        </div>  
    </article>   
</section>

app/views/shared/_new_like.html.erb
    <%= form_with model: @like,  url: "/users/#{params['user_id']}/posts/#{params['id']}/likes", class: 'button_to', method: :post , local: true do |form|%>
        <%= form.submit "Like", class: 'button' %>
    <% end %>

app/views/shared/_post_comments.html.erb
<div class="comments__info">                
    <% post.recent_comments.each do |comment| %>
        <p> 
            <span>
                <%= comment.author.name %>: <%= comment.text %>
            </span>
        </p>            
    <% end %>                
</div>

app/views/shared/_post_content.html.erb
<div class="cards__info">
    <h2 class="cards__title">Post : <%= post.title %> <%= writer %></h2>
    <p><%= post_content %></p>
    <h4 class="cards__item__ra">Comments: <span><%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %></span></h4>
</div>

app/views/shared/_user_card.html.erb
<article class="cards">            
    <img class="cards__img" src=<%= user.photo %> alt="user-photo">
    <div class="cards__info grid">
        <h2 class="cards__title"><%= link_to user.name, user %></h2>
        <h4 class="cards__item__ra">Number of posts: <%= user.posts_counter %></h4>
    </div>
</article>

app/views/users/index.html.erb
<section class="container grid">  
    <% @users.each do |user| %>
        <%= render 'shared/user_card', user:user %>
    <% end %>   

</section>

app/views/users/show.html.erb
<section class="container grid">
    <%= render 'shared/user_card', user:@user %>  
    <p class="user-bio"><%= @user.bio %></p>
    
    <% @user.recent_posts.each do |post| %>
        <%= link_to user_post_path(@user.id, post.id) do %>
        <%= render 'shared/post_content', post:post, post_content:post.text.first(250).concat('...'), writer:'' %>
        <% end %>        
    <% end %> 
    
    <div class="btn__holder">
        <button class="button">
        <%= link_to "See all posts", user_posts_path(@user), class:"text-button" %>
        </button>
    </div>
</section>